import type { Metadata } from "next";
import "./globals.css";
import { Nunito } from "next/font/google"
import Navbar from "@/components/ui/navbar";
import RegisterModal from "@/components/models/register-modal";
import ToasterProvider from "./providers/ToasterProvider";
import LoginModal from "@/components/models/login-modal";
import getCurrentUser from "@/actions/get-current-user";
import { auth } from "@/auth";
import RentModal from "@/components/models/rent-modal";

const font = Nunito({
  subsets: ["latin"]
})
export const metadata: Metadata = {
  title: "Airbnb | Vacation rentals, cabins",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const currentUser = await getCurrentUser();
  return (
    <html lang="en">
      <body
        className={`${font.className} flex flex-col items-center`}
      >
        <ToasterProvider />
        <RentModal />
        <LoginModal />
        <RegisterModal />
        <Navbar currentUser={currentUser} />
        <div className="pb-20 pt-28">
          {children}
        </div>
      </body>
    </html>
  );
}
